### ISSUE TITLE
Node Embedding

### ISSUE THREAD

**Issue by A2Amir** [louisabraham/fastnode2vec#21]
can fastnode2vec operate on completely disconnected nodes from the graph?

like the graph below

A----->B--------->C  &nbsp; &nbsp;    D(disconnected node from the graph)

**Comment by LucaCappelletti94** [comment]
From what I understand of the fastnode2vec library, [it only loads edge lists](https://github.com/louisabraham/fastnode2vec/blob/bcf42b6434279bfe967f8baea0ce6aa81c865681/fastnode2vec/graph.py#L123). If it only loads edge lists and you have a node without edges, it won't appear in the edge list and, therefore, will not be considered in the embedding process.

Anyhow, do consider that for any embedding that only and exclusively uses the topology, disconnected nodes would only receive a random embedding far apart from all nodes. This is because they would solely be sampled as negative nodes that are not in the context of any other node.

For this library's implementation of Node2Vec, those nodes would not appear in the embedding as they are excluded in the edge list and the graph and would not even be sampled as negatives.

**Comment by louisabraham** [comment]
Thank you, I'm closing this issue now.
